title       = "vozvn"
baseURL     = "https://vozvn-cli.tamnd.com/"
description = "A command line for vozvn."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/vozvn-cli"
